# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e3796b7e35848229fc4f21bcb965a032f9caffdd5af1bffc8433feb6e1bbc25d2ea3506f7b3ec6097e141d406e12c4f807af19dfe80f6806822de5049b2b722

test:
  secret_key_base: c064b7cfd0feae08c4209f5e7c0393f6248cbeee8063626f2465c89c027b788d7a317413f78ce7942670ba8771ccadaae984278744ad02c8f8f5a66de2539144

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
